# apiVersion: v1
# kind: Namespace
# metadata:
#   name: teamspeak
#   labels:
#     name: teamspeak
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamspeak-pvc
  namespace: default
  labels:
    app: teamspeak
spec:
  storageClassName: nfs-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jts3servermod-pvc
  namespace: default
spec:
  resources:
    requests:
      storage: 1G
  storageClassName: nfs-sc
  accessModes:
  - ReadWriteMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  teamspeak
  namespace: default
  labels:
    app:  teamspeak
spec:
  selector:
    matchLabels:
      app: teamspeak
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  teamspeak
      annotations:
         k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "teamspeak-network",
            "ips": ["10.132.132.132/24"]
          }]
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 1
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 1  
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name:  teamspeak
        image:  teamspeak:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          # limits:
          #   cpu: 100m
          #   memory: 100Mi
        # livenessProbe:
        #   tcpSocket:
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        env:
        - name: TS3SERVER_LICENSE
          value: accept
        - name: TS3SERVER_DB_PLUGIN
          value: ts3db_mariadb
        - name: TS3SERVER_DB_HOST
          value: 10.10.10.102
        - name: TS3SERVER_DB_USER
          value: teamspeak
        - name: TS3SERVER_DB_PASSWORD
          value: Wy87uHV3K!hLMUsQj&@!
        - name: TS3SERVER_DB_NAME
          value: teamspeak
        - name: TS3SERVER_DB_SQLCREATEPATH
          value: create_mariadb
        ports:
        # - name:  server-query
        #   containerPort:  10011
        - name: file-transfer
          containerPort: 30033
        - name: voice
          containerPort: 9987
          protocol: UDP
        - name: server-query
          containerPort: 10011
          protocol: TCP
        volumeMounts:
        - name: teamspeak-claim
          mountPath: /var/ts3server/
      - name: jts3servermod
        image: phaldan/jts3servermod
        resources:
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
        volumeMounts:
        - name: jts3servermod-claim
          mountPath: /JTS3ServerMod/config
      volumes:
        - name: teamspeak-claim
          persistentVolumeClaim:
            claimName: teamspeak-pvc
        - name: jts3servermod-claim
          persistentVolumeClaim:
            claimName: jts3servermod-pvc

      restartPolicy: Always

---

