apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uptime-kuma
  name: uptime-kuma
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "services-network",
            "ips": ["10.10.10.118/24"]
          }]
      labels:
        app: uptime-kuma
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 65534
      containers:
        - image: louislam/uptime-kuma
          name: uptime-kuma
          ports:
            - containerPort: 3001
              hostPort: 3001
              protocol: TCP
          resources:
            requests:
              memory: "400Mi"
          volumeMounts:
            - mountPath: /app/data
              name: uptime-kuma-volume
      dnsConfig: 
        nameservers:
          - 10.10.10.10
          - 10.10.10.11
      restartPolicy: Always
      volumes:
        - name: uptime-kuma-volume
          nfs:
            server: 10.0.0.2
            path: /mnt/user/kubernetes/volumes/uptime-kuma
            readOnly: false
