apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: uptime-kuma
  name: uptime-kuma
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-sc"
  resources:
    requests:
      storage: 100Mi
