apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitea
  name: gitea
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "services-network",
            "ips": ["10.10.10.108/24"]
          }]
      labels:
        app: gitea
    spec:
      containers:
        - image: gitea/gitea:latest
          name: gitea
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
            - containerPort: 2222
              hostPort: 2222
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: gitea-claim
              readOnly: false
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
      restartPolicy: Always
      volumes:
        - name: gitea-claim
          persistentVolumeClaim:
            claimName: gitea
      dnsConfig: 
        nameservers:
          - 10.10.10.10
          - 10.10.10.11
status: {}
