apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: gitea
  name: gitea
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: "web"
      port: 80
      targetPort: 3000
    - name: "2222"
      port: 2222
      targetPort: 2222
  selector:
    io.kompose.service: gitea
  loadBalancerIP: 10.10.10.108
status:
  loadBalancer: {}
