apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: gitea
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-sc"
  resources:
    requests:
      storage: 100Mi
status: {}
