apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: gitea
  name: gitea
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gitea
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/gitea-default: "true"
        io.kompose.service: gitea
    spec:
      containers:
        - image: gitea/gitea:1.20.3-rootless
          name: gitea
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
            - containerPort: 2222
              hostPort: 2222
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/gitea
              name: gitea-claim0
            - mountPath: /etc/gitea
              name: gitea-claim1
            - mountPath: /etc/timezone
              name: gitea-claim2
              readOnly: true
            - mountPath: /etc/localtime
              name: gitea-claim3
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: gitea-claim0
          persistentVolumeClaim:
            claimName: gitea-claim0
        - name: gitea-claim1
          persistentVolumeClaim:
            claimName: gitea-claim1
        - name: gitea-claim2
          persistentVolumeClaim:
            claimName: gitea-claim2
            readOnly: true
        - name: gitea-claim3
          persistentVolumeClaim:
            claimName: gitea-claim3
            readOnly: true
status: {}
