apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gitea-claim1
  name: gitea-claim1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-sc"
  resources:
    requests:
      storage: 100Mi
status: {}
