apiVersion: apps/v1
#kind: DaemonSet
kind: Deployment
metadata:
  name: pihole-deployment
  labels:
    app: pihole
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "services-network",
            "ips": ["10.10.10.10/24", "10.10.10.11/24"]
          }]
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 1
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 1  
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: pihole
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        volumeMounts:
        - name: etc-pihole
          mountPath: /etc/pihole
        - name: etc-dnsmasq
          mountPath: /etc/dnsmasq.d
        - name: var-log
          mountPath: /var/log
        - name: var-log-lighttpd
          mountPath: /var/log/lighttpd
        - name: regex
          mountPath: /etc/pihole/regex.list
          subPath: regex.list
        - name: whitelist
          mountPath: /etc/pihole/whitelist.txt
          subPath: whitelist.txt
        - name: adlists
          mountPath: /etc/pihole/adlists.list
          subPath: adlists.list
        - name: custom
          mountPath: /etc/pihole/custom.list
          subPath: custom.list
        env:
        - name: PIHOLE_DNS_
          value: 127.0.0.1#5053
        - name: WEBPASSWORD
          valueFrom: 
            secretKeyRef:
              name: pihole
              key: admin-pw
        - name: INTERFACE
          value: net1
        readinessProbe:
            exec:
              command: ['dig', '@127.0.0.1', 'google.com']
            timeoutSeconds: 20
            initialDelaySeconds: 5
            periodSeconds: 60
        resources:
          requests:
            memory: "100Mi"
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args: ["proxy-dns"]
        env:
          - name: TUNNEL_DNS_ADDRESS
            value: "0.0.0.0"
          - name: TUNNEL_DNS_UPSTEAM
            value: "https://1.1.1.2/dns-query,https://1.0.0.2/dns-query,https://9.9.9.9/dns-query"
          - name: TUNNEL_DNS_PORT
            value: "5053"
        resources:
          requests:
            memory: "100Mi"
      nodeSelector: 
        #beta.kubernetes.io/arch: arm64
      volumes:
      - name: etc-pihole
        emptyDir:
          medium: Memory
      - name: etc-dnsmasq
        emptyDir:
          medium: Memory
      - name: var-log
        emptyDir:
          medium: Memory
      - name: var-log-lighttpd
        emptyDir:
          medium: Memory
      - name: regex
        configMap:
          name: pihole-regex.list
          items:
            - key: regex.list
              path: regex.list
      - name: whitelist
        configMap:
          name: pihole-whitelist.txt
          items:
            - key: whitelist.txt
              path: whitelist.txt
      - name: adlists
        configMap:
          name: pihole-adlists.list
          items:
            - key: adlists.list
              path: adlists.list
      - name: custom
        configMap: 
          name: pihole-custom.list
          items:
          - key: custom.list
            path: custom.list
      