apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: reactive-resume
  name: reactive-resume
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reactive-resume
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/reactive-resume-default: "true"
        io.kompose.service: reactive-resume
    spec:
      nodeSelector: 
        beta.kubernetes.io/arch: amd64
      containers:
        - name: reactive-resume
          env:
            - name: GOOGLE_API_KEY
            - name: GOOGLE_CLIENT_SECRET
            - name: JWT_EXPIRY_TIME
              value: "604800"
            - name: JWT_SECRET
              value: change-me-to-something-secure
            - name: MAIL_FROM_EMAIL
              value: noreply@rxresu.me
            - name: MAIL_FROM_NAME
              value: Reactive Resume
            - name: MAIL_HOST
            - name: MAIL_PASSWORD
            - name: MAIL_PORT
            - name: MAIL_USERNAME
            - name: PDF_DELETION_TIME
            - name: POSTGRES_DB
              value: reactive-resume
            - name: POSTGRES_HOST
              value: 10.10.10.110
            - name: POSTGRES_PASSWORD
              value: 4seduaTtSGexT6GUQIuP
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_SSL_CERT
            - name: POSTGRES_USER
              value: rr
            - name: PUBLIC_GOOGLE_CLIENT_ID
            - name: PUBLIC_SERVER_URL
              value: http://10.10.10.109:3100
            - name: PUBLIC_URL
              value: http://10.10.10.109:3000
            - name: SECRET_KEY
              value: change-me-to-something-secure
            - name: STORAGE_ACCESS_KEY
            - name: STORAGE_BUCKET
            - name: STORAGE_ENDPOINT
            - name: STORAGE_REGION
            - name: STORAGE_SECRET_KEY
            - name: STORAGE_URL_PREFIX
          image: amruthpillai/reactive-resume:server-latest
          ports:
            - containerPort: 3100
              protocol: TCP
          resources: 
            limits:
              memory: "300Mi"
        - name: reactive-resume-client
          env:
            - name: PUBLIC_GOOGLE_CLIENT_ID
            - name: PUBLIC_SERVER_URL
              value: http://10.10.10.109:3100
            - name: PUBLIC_URL
              value: http://10.10.10.109:3000
          image: amruthpillai/reactive-resume:client-latest    
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: 
            limits:
              memory: "300Mi"
      restartPolicy: Always
status: {}
