apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.10.10.9-10.10.10.99

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-l2ad
  namespace: metallb-system
