apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.10.10.9-10.10.10.254
  - 10.101.101.2-10.101.101.254
  - 10.132.132.132-10.132.132.132
---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-l2ad
  namespace: metallb-system
