apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: services-network
spec:
  config: '{
      "cniVersion": "0.3.0",
      "name": "services-network",
      "type": "macvlan",
      "master": "eth0.4",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "routes": [
          { "dst": "0.0.0.0/0", "gw": "10.10.10.1" }
        ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: exposed-services-network
spec:
  config: '{
      "cniVersion": "0.3.0",
      "name": "exposed-services-network",
      "type": "macvlan",
      "master": "eth0.6",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "routes": [
          { "dst": "0.0.0.0/0", "gw": "10.101.101.1" }
        ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: teamspeak-network
spec:
  config: '{
      "cniVersion": "0.3.0",
      "name": "teamspeak-network",
      "type": "macvlan",
      "master": "eth0.7",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "routes": [
          { "dst": "0.0.0.0/0", "gw": "10.132.132.1" }
        ]
      }
    }'