apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-deployment
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [{
            "name": "exposed-services-network-default",
            "ips": ["10.101.101.102/24"]
          },
          {
            "name": "iot-network",
            "ips": ["192.168.3.2/24"]
          }]
      labels:
        app: home-assistant
    spec:
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 1
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 1  
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:2024.6
        ports:
        - name: web
          containerPort: 8123
          protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /config
      dnsConfig: 
        nameservers:
          - 10.10.10.10
          - 10.10.10.11
      volumes:
        - name: config
          nfs:
            server: 10.0.0.2
            path: /mnt/user/kubernetes/volumes/home-assistant/
            readOnly: false