apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: firefly-iii-upload
  name: firefly-iii-upload
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
