apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: firefly-iii
  name: firefly-iii
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: firefly-iii
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --
        kompose.version: 1.22.0 (955b78124)
      labels:
        io.kompose.service: firefly-iii
    spec:
      containers:
        - name: firefly-iii-core
          image: fireflyiii/core:latest
          ports:
            - containerPort: 8080
              hostPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html/storage/upload
              name: firefly-iii-upload
          envFrom:
          - configMapRef:
              name: firefly-iii-env
        # - name: firefly-iii-importer
        #   image: fireflyiii/data-importer:latest
        #   ports:
        #     - containerPort: 8080
        #   resources: {}
        #   volumeMounts:
        #     - mountPath: /etc/apache2/ports.conf
        #       name: ports
        #     - mountPath: /etc/apache2/sites-enabled/000-default.conf
        #       name: 000-default
        #   envFrom:
        #   - configMapRef:
        #       name: firefly-iii-importer-env
        # - name: firefly-iii-cron
        #   args: 
        #     - sh
        #     - -c
        #     - echo "0 3 * * * wget -qO- http://localhost:8080/api/v1/cron/REPLACEME" | crontab - && crond -f -L /dev/stdout
        #   image: alpine
        #   ports:
        #     - containerPort: 8081
        #   resources: {}
      restartPolicy: Always
      volumes:
        - name: firefly-iii-upload
          persistentVolumeClaim:
            claimName: firefly-iii-upload
status: {}
