apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy-deployment
  labels:
    app: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 1
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 1  
      containers:
      - name: dashy
        image: lissy93/dashy
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /app/user-data/
          name: dashy-volume
      volumes:
      - name: dashy-volume
        persistentVolumeClaim:
          claimName: dashy-pvc