apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy-deployment
  labels:
    app: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
      - name: dashy
        image: lissy93/dashy
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /app/public/
          name: dashy-volume
        resources:
          limits:
            cpu: "0.008"
            memory: "800Mi"
          requests:
            cpu: "0.002"
            memory: "200Mi" 
      volumes:
      - name: dashy-volume
        persistentVolumeClaim:
          claimName: dashy-pvc