# apiVersion: v1
# kind: Service
# metadata:
#   creationTimestamp: null
#   labels:
#     app: dashy
#   name: dashy-deployment
# spec:
#   ports:
#   - port: 80
#     protocol: TCP
#     targetPort: 8080
#   selector:
#     app: dashy
#   type: LoadBalancer
#   loadBalancerIP: 10.10.10.111
# status:
#   loadBalancer: {}
